# Generated by Django 3.1 on 2021-03-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name': 'Channel Subscription Link',
                'verbose_name_plural': 'Channel Subscription Links',
            },
        ),
        migrations.CreateModel(
            name='Comment_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name': 'Video link for commenting',
                'verbose_name_plural': 'Video links for commenting',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField(max_length=5000)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
