# Generated by Django 3.1 on 2021-03-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channels',
            options={'verbose_name': '3 - Channel Subscription Link', 'verbose_name_plural': '3 - Channel Subscription Links'},
        ),
        migrations.AlterModelOptions(
            name='comment_links',
            options={'verbose_name': '2 - Video link for commenting', 'verbose_name_plural': '2 - Video links for commenting'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '1 - Comment', 'verbose_name_plural': '1 - Comments'},
        ),
    ]
